In [67]:
import numpy as np 

def calculate (L):
    n=len(L)
    if (n!=9):
        print ("List must contain nine numbers.")
    else:
        mat = np.array(L)
        X=(mat.reshape(3,3))
        print (X)
        x=(X[0:1])
        y=(X[1:2])
        z=(X[2:3])
        d = np.vstack([x,y,z])
        return {
            'mean': [np.mean(X, axis = 0),np.mean(X, axis = 1), np.mean(X)],
            'variance': [np.var(X, axis =0), np.var(X , axis=1), np.var(X)],
            'standard deviation': [np.std(X, axis = 0), np.std(X, axis = 1), np.std(X)],
            'max': [np.max(X, axis = 0), np.max(X, axis = 1), np.max(X)],
            'min': [np.min(X, axis = 0), np.min(X, axis = 1), np.min(X)],
            'sum': [np.sum(X, axis = 0), np.sum(X, axis = 1), np.sum(X)]
        }
        

calculate ([0,1,2,3,4,5,6,7,8])
    

[[0 1 2]
 [3 4 5]
 [6 7 8]]


{'mean': [array([3., 4., 5.]), array([1., 4., 7.]), 4.0],
 'variance': [array([6., 6., 6.]),
  array([0.66666667, 0.66666667, 0.66666667]),
  6.666666666666667],
 'standard deviation': [array([2.44948974, 2.44948974, 2.44948974]),
  array([0.81649658, 0.81649658, 0.81649658]),
  2.581988897471611],
 'max': [array([6, 7, 8]), array([2, 5, 8]), 8],
 'min': [array([0, 1, 2]), array([0, 3, 6]), 0],
 'sum': [array([ 9, 12, 15]), array([ 3, 12, 21]), 36]}